### PR TITLE
SQL-170: Map BSON boolean to JDBC boolean instead of bit

### PR DESCRIPTION
**Pull request by EthanHardyMongo**
I modified BsonTypeInfo.java so that BSON_BOOL maps BSON boolean to JDBC Boolean. Additionally, I changed the integration tests that were expecting sql type BIT to instead expect sql type BOOLEAN.

### CODE REVIEW

**Comment by mattChiaravalloti** [comment]
Some nits about the PR title (which ultimately becomes the commit message):
- Let's try to start with present tense active verbs (changed `Mapped` => `Map`)
- No need to comment on test updates for something like this, that's always implied!

**Review by mattChiaravalloti — CHANGES_REQUESTED** [review]
This looks good but it looks like there are failures on evergreen! We can look into what else needs to be changed together tomorrow 👍

**Review by bucaojit — CHANGES_REQUESTED** [review]
Nice work getting your first PR up!  🎉 

There are a few integration tests still failing because the type for `BIT` which is -7 is still in a few of the tests that return the DATA_TYPE.  
If you find those and replace them with 16, which is the value for [BOOLEAN](https://github.com/JetBrains/jdk8u_jdk/blob/94318f9185757cc33d2b8d527d36be26ac6b7582/src/share/classes/java/sql/Types.java#L259) then the integration tests will pass.

**Review by mattChiaravalloti — APPROVED** [review]
Great work! When you get a second approval you can comment "evergreen merge" on this PR and that'll result in your first ticket being merged 🎊

**Review by bucaojit — APPROVED** [review]
LGTM!

Good job getting the integration tests working! 🔢

**Pull request merged**
