### PR TITLE
SQL-1675: Remove deprecated format, formatVersion, and dialect options from JDBC driver 

### PR DESCRIPTION
**Pull request by EthanHardyMongo**

### CODE REVIEW

**Review by mattChiaravalloti — APPROVED** [review]
lgtm 🔬

**Comment by bucaojit** [comment]
@EthanHardyMongo changes look good and nice to see the integration test pass.  Let's hold off on merging this just yet until I can confirm that the change has made it in time for the ADF release.  Otherwise it would have to wait until the next Tuesday release.

**Review by bucaojit — COMMENTED** [review]
I see my MHOUSE-8151 change didn't make it into the mongohouse [branch v20231107](https://github.com/10gen/mongohouse/tree/v20231107).  So I added the tag for fix version [v20231114](https://jira.mongodb.org/issues/?jql=project+%3D+MHOUSE+AND+fixVersion+%3D+v20231114) which is next Tuesday.  Let's hold off on merging this until after that is released.

**Comment by EthanHardyMongo** [comment]
evergreen merge

**Pull request merged**
