### PR TITLE
SQL-795: Allow deserializing empty json schemas

### PR DESCRIPTION
**Pull request by nbagnard**

### CODE REVIEW

**Review by rychipman — CHANGES_REQUESTED** [review]
my only request is that we add a regression test for this fix!

**Comment by nbagnard** [comment]
@rychipman : I've added a unit test only because I think that it should be enough and with the current bug on our local ADL it is a little bit tricky to add an integration test.

**Review by rychipman — APPROVED** [review]
Unit test SGTM -- thanks!
LGTM

**Comment by nbagnard** [comment]
evergreen merge

**Comment by nbagnard** [comment]
evergreen merge

**Comment by bucaojit** [comment]
evergreen merge

**Pull request merged**
